services:
  - type: web
    name: camera-store
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
